@startuml Consultation de Rendez-vous

skinparam backgroundColor white
title Séquence - Consultation de Rendez-vous

actor Patient
participant Frontend
participant "API Gateway" as GW
participant "RDV Service" as RDV
database "PostgreSQL\nrdvdb" as DB
participant "Docteur Service" as DOC

Patient -> Frontend : Voir mes rendez-vous
Frontend -> GW : GET /api/rdv
GW -> RDV : GET /rdv
RDV -> DB : Lire tous RDV
DB --> RDV : Liste RDV

RDV -> DOC : GET /docteurs/{id} (Feign)
DOC --> RDV : Données docteur

RDV --> GW : RDV + Docteur
GW --> Frontend : Liste complète
Frontend --> Patient : Affichage rendez-vous

@enduml
